services:
  se_es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.0
    container_name: ${ESNODE01_NAME}
    environment:
      - node.name=${ESNODE01_NAME}
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - ELASTICSEARCH_USERNAME=${ELASTICSEARCH_USERNAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - elsou-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - data_net
    healthcheck:
      test: ["CMD-SHELL", "curl -s -u ${ELASTICSEARCH_USERNAME}:${ELASTIC_PASSWORD} http://localhost:9200/_cluster/health | grep -vq '\"status\":\"red\"'"]
      interval: 20s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  se_api:
    build:
      context: ./packages/api
      dockerfile: Dockerfile.dev
    container_name: se_api
    environment:
      - ES_URL=${ELASTICSEARCH_URL}
      - ES_USERNAME=${ELASTICSEARCH_USERNAME}
      - ES_PASSWORD=${ELASTIC_PASSWORD}
      - ES_APIKEY=${ELASTICSEARCH_APIKEY}
      - ES_DICT_INDEX_NAME=dicionario_cursos
      - IES_DICT_INDEX_NAME=dicionario_ies
    ports:
      - "8080:8080"
    volumes:
      - ./packages/api:/app:z
      - go-mod-cache:/root/go/pkg/mod
    networks:
      - data_net
    depends_on:
      se_es01:
        condition: service_healthy
    restart: unless-stopped

  se_bulker:
    build:
      context: ./packages/bulker
    container_name: se_bulker
    environment:
      - ELASTICSEARCH_URL=${ELASTICSEARCH_URL}
      - ELASTICSEARCH_APIKEY=${ELASTICSEARCH_BULKER_APIKEY}
      - ES_INDEX_NAME=cursos
      - ES_DICT_INDEX_NAME=dicionario_cursos
      - JSON_FILE_PATH=/data/dados_curso_completo.json
      - IES_INDEX_NAME=ies
      - IES_JSON_FILE_PATH=/data/dados_ies.json
      - IES_DICT_INDEX_NAME=dicionario_ies
    volumes:
      - ./packages/bulker/data:/data:ro
    networks:
      - data_net
    depends_on:
      se_es01:
        condition: service_healthy
    profiles: ["bulker"]

  se_front:
    build:
      context: ./packages/front
      dockerfile: Dockerfile.dev
    container_name: se_front
    environment:
      - NODE_ENV=development
      - API_URL=${API_URL}
      - FORCE_COLOR=1
      - WATCHPACK_POLLING=true
    ports:
      - "3000:3000"
    volumes:
      - ./packages/front:/app:z
      - node_modules-data:/app/node_modules
      - /app/.next
    networks:
      - data_net
    depends_on:
      se_es01:
        condition: service_healthy
      # se_api:
      #   condition: service_started
    restart: unless-stopped

volumes:
  elsou-data:
    driver: local
  go-mod-cache:
    driver: local
  node_modules-data:
    driver: local

networks:
   data_net:
    name: data_net
    driver: bridge